"""Bake a bounded set of phone glyph textures. Does not distribute a font file.

Uses the Windows Arial installation by default; --font accepts an equivalent TTF.
Metrics and glyphs must be regenerated together. Runtime performs no rasterization.
"""
from pathlib import Path
import argparse, math
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', default='C:/Windows/Fonts/arial.ttf')
    args = parser.parse_args()
    font = ImageFont.truetype(args.font, 48)
    out = ROOT/'assets/ui'
    out.mkdir(parents=True, exist_ok=True)
    advances = []
    for code in range(32, 127):
        ch = chr(code)
        advance = float(font.getlength(ch))
        advances.append(advance)
        image = Image.new('RGBA', (math.ceil(advance)+8, 64))
        ImageDraw.Draw(image).text((4, 0), ch, font=font, fill='white', anchor='la')
        image.save(out/f'phone-glyph-{code:03d}.png')
    Image.new('RGBA', (1,1), 'white').save(out/'phone-pixel.png')
    source = '''// Generated by tools/build_phone_font.py alongside the glyph PNGs.
namespace Bloodlines.Core
{
    public sealed partial class PhoneOverlay
    {
        private static readonly float[] Advances = {
            %s
        };
    }
}
''' % ', '.join(f'{n:.6f}f' for n in advances)
    (ROOT/'src/Bloodlines/Core/PhoneOverlay.Metrics.cs').write_text(source, encoding='utf-8', newline='\r\n')
    print('Baked 95 glyphs and a solid pixel; generated matching advances.')

if __name__ == '__main__':
    main()
