"""Render docs/CAMPAIGN.md from the generated campaign data.

Keeps the human-readable campaign map in sync with data/missions.tsv rather than
letting a hand-maintained table drift away from the bible.

    python3 tools/render_campaign_doc.py
"""

import csv
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MISSIONS = os.path.join(REPO, 'data', 'missions.tsv')
DIALOGUE = os.path.join(REPO, 'data', 'dialogue.tsv')
OUT = os.path.join(REPO, 'docs', 'CAMPAIGN.md')

# Missions with a Mission class wired into MissionCatalog.Scripted.
PLAYABLE = {'M01', 'M02', 'M03', 'M04', 'M05', 'M06', 'M07', 'M08', 'M09', 'M10',
            'M11', 'M12', 'M13', 'SM01', 'SM02', 'SM03'}

ACTS = [
    (1, 22, 'Act I — The Bleeding Trail',
     'The accidental reunion at the Terminal Island dry-docks triggers a containment '
     'scramble across Los Santos, culminating in the four-part Port Heist and the '
     'destruction of the Cypress Foundry base.'),
    (23, 48, 'Act II — The Squeeze',
     'Exiled to Blaine County, the trio wages asymmetrical warfare from a Cold War radar '
     'bunker — mid-air boardings, deep-sea rig demolition — before fighting back south.'),
    (49, 70, 'Act III — Scorched Earth',
     'Urban warfare across Los Santos: triple-skyscraper raids, coastal train assault, and '
     'the LSIA runway holdout.'),
]


def read(path):
    with open(path) as handle:
        return list(csv.DictReader(handle, delimiter='\t'))


def main():
    rows = read(MISSIONS)
    missions = {int(row['number']): row for row in rows if row.get('kind', 'main') != 'solo'}
    solo = [row for row in rows if row.get('kind') == 'solo']
    cues = read(DIALOGUE)

    lines_by_mission = {}
    for cue in cues:
        lines_by_mission.setdefault(cue['mission'], 0)
        lines_by_mission[cue['mission']] += 1

    out = ['# Campaign',
           '',
           'Generated from `data/missions.tsv` by `tools/render_campaign_doc.py` — which is '
           'itself generated from the omnibus bible by `tools/parse_bible.py`. Edit the bible '
           'and re-run; do not edit this file.',
           '',
           '**{} main missions · {} solo missions · {} written dialogue lines · {} playable.**'.format(
               len(missions), len(solo), len(cues), len(PLAYABLE)),
           '',
           'Solo missions are listed under the act they belong to and slot into the main '
           'line after the mission named in their row.',
           '']

    for low, high, title, blurb in ACTS:
        out += ['', '## {}'.format(title), '', blurb, '',
                '| # | Mission | Setting | Objective | Lines | Status |',
                '|---|---|---|---|---|---|']
        act_rows = []
        for number in range(low, high + 1):
            if number in missions:
                act_rows.append(missions[number])
            act_rows.extend(row for row in solo
                            if row.get('insert_after') and int(row['insert_after']) == number)

        for row in act_rows:
            setting = ' · '.join(part for part in
                                 [row['location'], row['time'], row['weather']] if part)
            objective = re.sub(r'\s+', ' ', row['hud']).strip()
            if len(objective) > 90:
                objective = objective[:87].rstrip() + '…'
            status = '**playable**' if row['id'] in PLAYABLE else 'written'
            title = row['title'].title()
            if row.get('kind') == 'solo':
                title = '↳ *{} solo* — {}'.format(row['owner'].title(), title)
            out.append('| {} | {} | {} | {} | {} | {} |'.format(
                row['id'], title, setting, objective,
                lines_by_mission.get(row['id'], 0), status))

    out += ['', '## Status key', '',
            '- **playable** — a `Mission` class exists and is registered in `MissionCatalog`.',
            '- **written** — setting, objective, beats and dialogue are in the data files and '
            'load at runtime; no mission script yet.', '']

    with open(OUT, 'w') as handle:
        handle.write('\n'.join(out))
    print('wrote docs/CAMPAIGN.md ({} missions)'.format(len(missions)))


if __name__ == '__main__':
    main()
